version: "3.8"

networks:
  spark-cluster:
    external: true
    name: spark-cluster

services:
  spark-master:
    image: joaovictortr/spark-standalone:latest
    build:
      context: .
      args:
        SPARK_VERSION: "3.0.0"
        HADOOP_VERSION: "2.7"
    container_name: spark-master
    networks:
      - spark-cluster
    environment:
      SPARK_MASTER_HOST: "spark-master"
    volumes:
      - ./spark-data:/data
      - ./spark-conf:/opt/spark/conf
    ports:
      - 8080:8080
      - 7070:7070
    command: ["master"]

  spark-worker:
    image: joaovictortr/spark-standalone:latest
    build:
      context: .
      args:
        SPARK_VERSION: "3.0.0"
        HADOOP_VERSION: "2.7"
    networks:
      - spark-cluster
    volumes:
      - ./spark-data:/data
      - ./spark-conf:/opt/spark/conf
    command: ["worker", "spark://spark-master:7077"]

  spark-shell:
    image: joaovictortr/spark-standalone:latest
    container_name: spark-shell
    build:
      context: .
      args:
        SPARK_VERSION: "3.0.0"
        HADOOP_VERSION: "2.7"
    networks:
      - spark-cluster
    volumes:
      - ./spark-data:/data
      - ./spark-conf:/opt/spark/conf
    command: ["shell", "spark://spark-master:7077"]
